import { useState } from 'react'
import { Box, Dialog, Flex, Icon, Input, Menu, Portal, Spinner, Text } from '@chakra-ui/react'
import {
  LuCheck,
  LuCopy,
  LuEllipsisVertical,
  LuKeyRound,
  LuMail,
  LuPhone,
  LuUserMinus,
  LuUserPlus,
  LuUsers,
} from 'react-icons/lu'
import BrokersSkeleton from '@/components/skeletons/BrokersSkeleton'
import { Reveal } from '@/components/ui-kit/Reveal'
import EmptyState from '@/components/EmptyState'
import { Card } from '@/components/ui-kit/Card'
import RefreshButton from '@/components/ui-kit/RefreshButton'
import SourceNotice from '@/components/SourceNotice'
import useApiQuery from '@/hooks/useApiQuery'
import { createBroker, deleteBroker, fetchBrokers, validateBroker } from '@/data/brokersData'
import { SUPABASE_ENV } from '@/data/supabase'
import { COLORS } from '@/theme/colors'
import { notifyFailed, notifySaved } from '@/lib/notify'

const FONT = 'Inter, system-ui, sans-serif'
const HEADING_FONT = "'Plus Jakarta Sans', Inter, system-ui, sans-serif"
const MONO_FONT = "ui-monospace, SFMono-Regular, Menlo, Consolas, monospace"

const EMPTY_FORM = { firstName: '', lastName: '', mobileNumber: '', email: '' }

// autoComplete is off: these fields describe the broker, not the admin filling
// the form in, so the browser should not offer the admin's own details.
const FIELDS = [
  { key: 'firstName', label: 'First Name', placeholder: 'e.g. Juan' },
  { key: 'lastName', label: 'Last Name', placeholder: 'e.g. Dela Cruz' },
  { key: 'mobileNumber', label: 'Mobile Number', placeholder: 'e.g. 0917 123 4567', type: 'tel', inputMode: 'tel' },
  { key: 'email', label: 'Email Address', placeholder: 'e.g. juan@example.com', type: 'email' },
]

function initials(broker) {
  return `${broker.firstName[0] ?? ''}${broker.lastName[0] ?? ''}`.toUpperCase()
}

function formatShortDate(iso) {
  const date = new Date(iso)
  if (Number.isNaN(date.getTime())) return '—'
  return `${date.getMonth() + 1}/${date.getDate()}/${date.getFullYear()}`
}

function Field({ field, value, error, onChange, disabled }) {
  const id = `broker-${field.key}`
  return (
    <Box flex="1" minW={0}>
      <Text as="label" htmlFor={id} display="block" mb="6px" fontFamily={FONT} fontWeight="500" fontSize="13px" color={COLORS.heading}>
        {field.label}
      </Text>
      <Input
        id={id}
        type={field.type ?? 'text'}
        inputMode={field.inputMode}
        autoComplete="off"
        placeholder={field.placeholder}
        value={value}
        onChange={onChange}
        disabled={disabled}
        aria-invalid={error ? true : undefined}
        aria-describedby={error ? `${id}-error` : undefined}
        borderColor={error ? '#DC2626' : undefined}
      />
      {error ? (
        <Text id={`${id}-error`} mt="4px" fontFamily={FONT} fontSize="12px" color="#B91C1C">
          {error}
        </Text>
      ) : null}
    </Box>
  )
}

/** A value shown for copying: label, monospace value, and a Copy button that confirms. */
function CopyRow({ label, value }) {
  const [copied, setCopied] = useState(false)

  async function copy() {
    try {
      await navigator.clipboard.writeText(value)
      setCopied(true)
      setTimeout(() => setCopied(false), 1800)
    } catch {
      notifyFailed('Could not copy', new Error('Select the text and copy it instead.'))
    }
  }

  return (
    <Box>
      <Text fontFamily={FONT} fontWeight="500" fontSize="12px" color={COLORS.muted}>
        {label}
      </Text>
      <Flex mt="4px" align="center" gap="8px" h="40px" pl="12px" pr="4px" bg={COLORS.surface} border="1px solid" borderColor={COLORS.border} borderRadius="8px">
        <Text flex="1" minW={0} fontFamily={MONO_FONT} fontSize="14px" color={COLORS.heading} truncate userSelect="all">
          {value}
        </Text>
        <Flex
          as="button"
          type="button"
          align="center"
          gap="6px"
          h="32px"
          px="10px"
          flexShrink={0}
          borderRadius="6px"
          fontFamily={FONT}
          fontWeight="600"
          fontSize="12.5px"
          color={copied ? COLORS.activeBg : COLORS.heading}
          cursor="pointer"
          _hover={{ bg: COLORS.hoverBg }}
          aria-label={`Copy ${label.toLowerCase()}`}
          onClick={copy}
        >
          <Icon as={copied ? LuCheck : LuCopy} boxSize="14px" />
          {copied ? 'Copied' : 'Copy'}
        </Flex>
      </Flex>
    </Box>
  )
}

/**
 * The sign-in details of the account just created. The password is generated by
 * the server and exists nowhere else the portal can read, so this is the only
 * time it is shown.
 */
function CreatedCredentials({ account, onDone }) {
  return (
    <Box role="status" p="16px" borderRadius="10px" bg={COLORS.statusBg} border="1px solid" borderColor={COLORS.border}>
      <Flex align="center" gap="8px">
        <Icon as={LuKeyRound} boxSize="16px" color={COLORS.activeBg} />
        <Text fontFamily={HEADING_FONT} fontWeight="700" fontSize="15px" color={COLORS.heading}>
          Account created for {account.name}
        </Text>
      </Flex>
      <Text mt="6px" fontFamily={FONT} fontSize="13px" lineHeight="20px" color={COLORS.muted}>
        A confirmation email was sent to {account.email}. The broker must confirm it before they can sign in to the
        app. The password is not in that email, so give it to them yourself. It is shown only once: copy it before
        closing.
      </Text>
      <Flex mt="12px" direction="column" gap="10px">
        <CopyRow label="Email" value={account.email} />
        <CopyRow label="Temporary Password" value={account.password} />
      </Flex>
      <Box
        as="button"
        type="button"
        mt="14px"
        h="36px"
        px="16px"
        borderRadius="8px"
        bg={COLORS.surface}
        border="1px solid"
        borderColor={COLORS.border}
        color={COLORS.heading}
        fontFamily={FONT}
        fontWeight="600"
        fontSize="13px"
        cursor="pointer"
        _hover={{ bg: COLORS.hoverBg }}
        onClick={onDone}
      >
        Done, add another broker
      </Box>
    </Box>
  )
}

/** The account form. Errors show per field once someone has tried to submit. */
function AddBrokerForm({ disabled, onCreated }) {
  const [form, setForm] = useState(EMPTY_FORM)
  const [submitted, setSubmitted] = useState(false)
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')
  const [created, setCreated] = useState(null)

  const errors = submitted ? validateBroker(form) : {}
  const set = (key) => (event) => setForm((prev) => ({ ...prev, [key]: event.target.value }))
  const field = (spec) => (
    <Field key={spec.key} field={spec} value={form[spec.key]} error={errors[spec.key]} onChange={set(spec.key)} disabled={busy} />
  )

  async function handleSubmit(event) {
    event.preventDefault()
    setSubmitted(true)
    setError('')
    if (Object.keys(validateBroker(form)).length) return

    setBusy(true)
    try {
      const account = await createBroker(form)
      const name = `${form.firstName.trim()} ${form.lastName.trim()}`
      setCreated({ name, email: account.email, password: account.password })
      notifySaved('Broker account created', `A confirmation email was sent to ${account.email}.`)
      setForm(EMPTY_FORM)
      setSubmitted(false)
      onCreated()
    } catch (err) {
      setError(err.message)
      notifyFailed('Could not create the broker account', err)
    } finally {
      setBusy(false)
    }
  }

  return (
    <Card as="section" p={{ base: '18px', md: '22px' }} w={{ base: 'full', xl: '460px' }} flexShrink={0}>
      <Text as="h2" fontFamily={HEADING_FONT} fontWeight="700" fontSize="17px" color={COLORS.heading}>
        New Broker Account
      </Text>
      <Text mt="4px" fontFamily={FONT} fontSize="13px" color={COLORS.muted}>
        All fields are required. A temporary password is generated, and the broker gets a confirmation email.
      </Text>

      {created ? (
        <Box mt="18px">
          <CreatedCredentials account={created} onDone={() => setCreated(null)} />
        </Box>
      ) : (
        <Flex as="form" noValidate onSubmit={handleSubmit} direction="column" gap="14px" mt="18px">
          <Flex gap="14px" direction={{ base: 'column', sm: 'row' }}>
            {FIELDS.slice(0, 2).map(field)}
          </Flex>
          {FIELDS.slice(2).map(field)}

          {error ? (
            <Text role="alert" fontFamily={FONT} fontSize="13px" color="#B91C1C">
              {error}
            </Text>
          ) : null}

          <Flex
            as="button"
            type="submit"
            align="center"
            justify="center"
            gap="8px"
            h="40px"
            px="16px"
            mt="4px"
            alignSelf="flex-start"
            borderRadius="8px"
            bg={COLORS.brandGreen}
            color="#FFFFFF"
            fontFamily={FONT}
            fontWeight="600"
            fontSize="14px"
            cursor="pointer"
            disabled={disabled || busy}
            _hover={{ bg: '#00541F' }}
            _disabled={{ opacity: 0.55, cursor: 'not-allowed' }}
            _focusVisible={{ outline: '2px solid', outlineColor: COLORS.activeBg, outlineOffset: '2px' }}
          >
            {busy ? <Spinner size="sm" /> : <Icon as={LuUserPlus} boxSize="16px" />}
            Create Broker Account
          </Flex>
        </Flex>
      )}
    </Card>
  )
}

/** Row actions behind a three-dot button, the same menu the announcements and lots use. */
function BrokerActions({ broker, onRemove }) {
  return (
    <Menu.Root onSelect={({ value }) => value === 'remove' && onRemove()}>
      <Menu.Trigger
        aria-label={`Actions for ${broker.firstName} ${broker.lastName}`}
        title="More actions"
        display="flex"
        alignItems="center"
        justifyContent="center"
        boxSize="32px"
        borderRadius="8px"
        bg="transparent"
        color={COLORS.muted}
        cursor="pointer"
        flexShrink={0}
        _hover={{ bg: COLORS.hoverBg }}
        _focusVisible={{ outline: '2px solid', outlineColor: COLORS.activeBg, outlineOffset: '2px' }}
      >
        <Icon as={LuEllipsisVertical} boxSize="16px" />
      </Menu.Trigger>
      <Portal>
        <Menu.Positioner>
          <Menu.Content minW="170px">
            <Menu.Item value="remove" gap="8px" fontSize="13px" color="#DC2626" _hover={{ bg: '#FDECEC', color: '#B91C1C' }}>
              <Icon as={LuUserMinus} boxSize="14px" />
              Remove account
            </Menu.Item>
          </Menu.Content>
        </Menu.Positioner>
      </Portal>
    </Menu.Root>
  )
}

/** Confirms, then removes the broker's app login and their row. */
function RemoveBrokerDialog({ broker, onClose, onRemoved }) {
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')

  function close() {
    setError('')
    onClose()
  }

  async function handleRemove() {
    setBusy(true)
    setError('')
    try {
      await deleteBroker(broker.id)
      notifySaved('Broker account removed', `${broker.firstName} ${broker.lastName} can no longer sign in to the app.`)
      setError('')
      onRemoved()
    } catch (err) {
      setError(err.message)
      notifyFailed('Could not remove the broker account', err)
    } finally {
      setBusy(false)
    }
  }

  return (
    <Dialog.Root
      role="alertdialog"
      open={Boolean(broker)}
      onOpenChange={({ open }) => {
        if (!open && !busy) close()
      }}
      placement="center"
      size="sm"
    >
      <Portal>
        <Dialog.Backdrop />
        <Dialog.Positioner px="16px">
          <Dialog.Content borderRadius="16px">
            <Dialog.Header borderBottom="1px solid" borderColor={COLORS.border} py="18px">
              <Dialog.Title fontFamily={HEADING_FONT} fontSize="18px" color={COLORS.heading}>
                Remove broker account?
              </Dialog.Title>
            </Dialog.Header>
            <Dialog.Body py="18px">
              <Text fontFamily={FONT} fontSize="14px" lineHeight="22px" color={COLORS.muted}>
                {broker?.firstName} {broker?.lastName} ({broker?.email}) will be signed out of the app and their login
                deleted. This cannot be undone. To give them access again, create a new account.
              </Text>
              {error ? (
                <Text role="alert" mt="12px" fontFamily={FONT} fontSize="13px" color="#B91C1C">
                  {error}
                </Text>
              ) : null}
            </Dialog.Body>
            <Dialog.Footer borderTop="1px solid" borderColor={COLORS.border} py="16px" gap="10px">
              <Box
                as="button"
                type="button"
                h="40px"
                px="18px"
                borderRadius="8px"
                bg={COLORS.hoverBg}
                color={COLORS.heading}
                fontFamily={FONT}
                fontWeight="600"
                fontSize="14px"
                cursor="pointer"
                disabled={busy}
                onClick={close}
              >
                Cancel
              </Box>
              <Flex
                as="button"
                type="button"
                align="center"
                gap="8px"
                h="40px"
                px="16px"
                borderRadius="8px"
                bg="#B91C1C"
                color="#FFFFFF"
                fontFamily={FONT}
                fontWeight="600"
                fontSize="14px"
                cursor="pointer"
                disabled={busy}
                _hover={{ bg: '#991B1B' }}
                _disabled={{ opacity: 0.55, cursor: 'not-allowed' }}
                onClick={handleRemove}
              >
                {busy ? <Spinner size="sm" /> : null}
                Remove account
              </Flex>
            </Dialog.Footer>
          </Dialog.Content>
        </Dialog.Positioner>
      </Portal>
    </Dialog.Root>
  )
}

function BrokerRow({ broker, onRemove }) {
  return (
    <Flex align="center" gap="12px" py="12px" borderTop="1px solid" borderColor={COLORS.border} _first={{ borderTop: 'none' }}>
      <Flex
        align="center"
        justify="center"
        boxSize="36px"
        flexShrink={0}
        borderRadius="full"
        bg={COLORS.statusBg}
        color={COLORS.activeBg}
        fontFamily={HEADING_FONT}
        fontWeight="700"
        fontSize="12.5px"
      >
        {initials(broker)}
      </Flex>
      <Box minW={0} flex="1">
        <Text fontFamily={FONT} fontWeight="600" fontSize="14px" color={COLORS.heading} truncate>
          {broker.firstName} {broker.lastName}
        </Text>
        <Flex mt="2px" gap={{ base: '2px', md: '14px' }} direction={{ base: 'column', md: 'row' }} fontFamily={FONT} fontSize="12.5px" color={COLORS.muted}>
          <Flex align="center" gap="5px" minW={0}>
            <Icon as={LuMail} boxSize="12px" flexShrink={0} />
            <Text truncate>{broker.email}</Text>
          </Flex>
          <Flex align="center" gap="5px">
            <Icon as={LuPhone} boxSize="12px" flexShrink={0} />
            <Text>{broker.mobileNumber}</Text>
          </Flex>
        </Flex>
      </Box>
      <Text flexShrink={0} fontFamily={FONT} fontSize="12px" color={COLORS.subtle} display={{ base: 'none', sm: 'block' }}>
        {formatShortDate(broker.createdAt)}
      </Text>
      {onRemove ? <BrokerActions broker={broker} onRemove={onRemove} /> : null}
    </Flex>
  )
}

export default function BrokersPage() {
  const { data, loading, reload, refresh } = useApiQuery(fetchBrokers)
  const [removing, setRemoving] = useState(null)

  if (loading && !data) return <BrokersSkeleton />

  const brokers = data?.brokers ?? []

  return (
    <Reveal>
      <Flex direction="column" gap="20px">
        <Box maxW="600px">
          <Text
            as="h1"
            fontFamily={HEADING_FONT}
            fontWeight="700"
            fontSize={{ base: '26px', md: '32px' }}
            lineHeight="1.2"
            letterSpacing="-0.6px"
            color={COLORS.heading}
          >
            Add Brokers
          </Text>
          <Text mt="8px" fontFamily={FONT} fontSize="14px" lineHeight="22px" color={COLORS.muted}>
            Create broker accounts for sales partners. Each account is a login for the VHBC app.
          </Text>
        </Box>

        {data ? <SourceNotice source={data.source} envVar={SUPABASE_ENV} /> : null}

        <Flex gap="20px" direction={{ base: 'column', xl: 'row' }} align="flex-start">
          <AddBrokerForm disabled={data?.source !== 'database'} onCreated={reload} />

          <Card as="section" p={{ base: '18px', md: '22px' }} flex="1" minW={0} w="full">
            <Flex align="center" justify="space-between" gap="12px">
              <Text as="h2" fontFamily={HEADING_FONT} fontWeight="700" fontSize="17px" color={COLORS.heading}>
                Broker Accounts
              </Text>
              <Flex align="center" gap="10px">
                <Text fontFamily={FONT} fontSize="12.5px" color={COLORS.subtle}>
                  {brokers.length} total
                </Text>
                <RefreshButton onRefresh={refresh} label="Refresh brokers" size="32px" />
              </Flex>
            </Flex>
            <Box mt="10px" opacity={loading ? 0.6 : 1} transition="opacity 120ms ease">
              {brokers.length ? (
                brokers.map((broker) => (
                  <BrokerRow
                    key={broker.id}
                    broker={broker}
                    onRemove={data?.source === 'database' ? () => setRemoving(broker) : undefined}
                  />
                ))
              ) : (
                <EmptyState icon={LuUsers} title="No brokers yet" hint="Accounts you create will show up here, newest first." />
              )}
            </Box>
          </Card>
        </Flex>
      </Flex>

      <RemoveBrokerDialog
        broker={removing}
        onClose={() => setRemoving(null)}
        onRemoved={() => {
          setRemoving(null)
          reload()
        }}
      />
    </Reveal>
  )
}
