-- GLS price per sqm: one row holding a price for each lot category, the same
-- shape as erhd_price. The portal reads the first row (lowest id) and writes it
-- from "Update category prices".
--
-- Safe to re-run: the table and policies are left alone if they already exist.
-- Run once in the Supabase SQL Editor.
CREATE TABLE IF NOT EXISTS public.gls_price (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  regular       BIGINT,
  prime         BIGINT,
  prime_corner  BIGINT,
  user_id       UUID
);

ALTER TABLE public.gls_price ENABLE ROW LEVEL SECURITY;

-- Same access as erhd_price, when that table has policies.
DO $$
DECLARE
  pol record;
BEGIN
  FOR pol IN
    SELECT * FROM pg_policies WHERE schemaname = 'public' AND tablename = 'erhd_price'
  LOOP
    CONTINUE WHEN EXISTS (
      SELECT 1 FROM pg_policies
      WHERE schemaname = 'public' AND tablename = 'gls_price' AND policyname = pol.policyname
    );

    EXECUTE format(
      'CREATE POLICY %I ON public.gls_price AS %s FOR %s TO %s%s%s',
      pol.policyname,
      pol.permissive,
      pol.cmd,
      (SELECT string_agg(CASE WHEN role = 'public' THEN 'public' ELSE quote_ident(role) END, ', ')
       FROM unnest(pol.roles) AS role),
      COALESCE(' USING (' || pol.qual || ')', ''),
      COALESCE(' WITH CHECK (' || pol.with_check || ')', '')
    );
    RAISE NOTICE 'Added policy "%" to gls_price', pol.policyname;
  END LOOP;
END $$;

-- Make the new table visible to the API immediately.
NOTIFY pgrst, 'reload schema';
