-- Flyers Pictures gallery on the Projects & Lots page. Same shape as
-- project_dev / future_dev. Run once in the Supabase SQL Editor.
CREATE TABLE IF NOT EXISTS public.flyers (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  image_link    TEXT NOT NULL,
  user_id       UUID,
  project_name  TEXT
);

CREATE INDEX IF NOT EXISTS flyers_project_created_idx ON public.flyers (project_name, created_at DESC);

ALTER TABLE public.flyers ENABLE ROW LEVEL SECURITY;

-- Anyone can view flyers; signed-in portal users can add and delete them.
DROP POLICY IF EXISTS "flyers_read" ON public.flyers;
CREATE POLICY "flyers_read" ON public.flyers FOR SELECT USING (true);

DROP POLICY IF EXISTS "flyers_insert" ON public.flyers;
CREATE POLICY "flyers_insert" ON public.flyers FOR INSERT TO authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "flyers_delete" ON public.flyers;
CREATE POLICY "flyers_delete" ON public.flyers FOR DELETE TO authenticated USING (true);

-- Public bucket, so image_link is a plain public URL like the other galleries.
INSERT INTO storage.buckets (id, name, public)
VALUES ('flyers', 'flyers', true)
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS "flyers_bucket_read" ON storage.objects;
CREATE POLICY "flyers_bucket_read" ON storage.objects
  FOR SELECT USING (bucket_id = 'flyers');

DROP POLICY IF EXISTS "flyers_bucket_insert" ON storage.objects;
CREATE POLICY "flyers_bucket_insert" ON storage.objects
  FOR INSERT TO authenticated WITH CHECK (bucket_id = 'flyers');

DROP POLICY IF EXISTS "flyers_bucket_delete" ON storage.objects;
CREATE POLICY "flyers_bucket_delete" ON storage.objects
  FOR DELETE TO authenticated USING (bucket_id = 'flyers');

-- Make the new table visible to the API immediately.
NOTIFY pgrst, 'reload schema';
