-- Structured Future Projects content managed from Project Actions.
CREATE TABLE IF NOT EXISTS public.future_projects (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_code  TEXT NOT NULL,
  name          TEXT NOT NULL,
  location      TEXT NOT NULL,
  description   TEXT,
  image_url     TEXT NOT NULL,
  storage_path  TEXT NOT NULL,
  user_id       UUID,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Upgrade the earlier gallery-shaped table if that version was already run.
ALTER TABLE public.future_projects
  ADD COLUMN IF NOT EXISTS project_code TEXT,
  ADD COLUMN IF NOT EXISTS name TEXT,
  ADD COLUMN IF NOT EXISTS location TEXT,
  ADD COLUMN IF NOT EXISTS description TEXT,
  ADD COLUMN IF NOT EXISTS image_url TEXT,
  ADD COLUMN IF NOT EXISTS storage_path TEXT,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'future_projects' AND column_name = 'image_link'
  ) THEN
    EXECUTE 'UPDATE public.future_projects SET image_url = COALESCE(image_url, image_link)';
    -- New structured inserts no longer provide the legacy image_link column.
    EXECUTE 'ALTER TABLE public.future_projects ALTER COLUMN image_link DROP NOT NULL';
  END IF;

  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'future_projects' AND column_name = 'project_name'
  ) THEN
    EXECUTE 'UPDATE public.future_projects SET name = COALESCE(NULLIF(name, ''''), NULLIF(project_name, ''''))';
    EXECUTE 'UPDATE public.future_projects SET project_code = COALESCE(NULLIF(project_code, ''''), NULLIF(project_name, ''''))';
  END IF;
END $$;

UPDATE public.future_projects
SET
  project_code = COALESCE(NULLIF(project_code, ''), NULLIF(name, ''), 'UNKNOWN'),
  name = COALESCE(NULLIF(name, ''), 'Future Project'),
  location = COALESCE(location, ''),
  image_url = COALESCE(image_url, ''),
  storage_path = COALESCE(
    NULLIF(storage_path, ''),
    split_part(COALESCE(image_url, ''), '/object/public/future-projects/', 2),
    ''
  ),
  updated_at = COALESCE(updated_at, created_at, now());

ALTER TABLE public.future_projects
  ALTER COLUMN project_code SET NOT NULL,
  ALTER COLUMN name SET NOT NULL,
  ALTER COLUMN location SET NOT NULL,
  ALTER COLUMN image_url SET NOT NULL,
  ALTER COLUMN storage_path SET NOT NULL,
  ALTER COLUMN updated_at SET DEFAULT now(),
  ALTER COLUMN updated_at SET NOT NULL;

CREATE INDEX IF NOT EXISTS future_projects_updated_idx
  ON public.future_projects (updated_at DESC);

ALTER TABLE public.future_projects ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "future_projects_read" ON public.future_projects;
CREATE POLICY "future_projects_read" ON public.future_projects FOR SELECT USING (true);

DROP POLICY IF EXISTS "future_projects_insert" ON public.future_projects;
CREATE POLICY "future_projects_insert" ON public.future_projects
  FOR INSERT TO authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "future_projects_update" ON public.future_projects;
CREATE POLICY "future_projects_update" ON public.future_projects
  FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "future_projects_delete" ON public.future_projects;
CREATE POLICY "future_projects_delete" ON public.future_projects
  FOR DELETE TO authenticated USING (true);

INSERT INTO storage.buckets (id, name, public)
VALUES ('future-projects', 'future-projects', true)
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS "future_projects_bucket_read" ON storage.objects;
CREATE POLICY "future_projects_bucket_read" ON storage.objects
  FOR SELECT USING (bucket_id = 'future-projects');

DROP POLICY IF EXISTS "future_projects_bucket_insert" ON storage.objects;
CREATE POLICY "future_projects_bucket_insert" ON storage.objects
  FOR INSERT TO authenticated WITH CHECK (bucket_id = 'future-projects');

DROP POLICY IF EXISTS "future_projects_bucket_delete" ON storage.objects;
CREATE POLICY "future_projects_bucket_delete" ON storage.objects
  FOR DELETE TO authenticated USING (bucket_id = 'future-projects');

NOTIFY pgrst, 'reload schema';
