-- Annotated site maps: one uploaded image per project phase, with the COCO JSON
-- describing the lot polygons drawn on it. Same shape and policies as `flyers`.
-- Run once in the Supabase SQL Editor.
CREATE TABLE IF NOT EXISTS public.annotated_images (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  -- Public URL of the uploaded image in the `annotated-images` bucket below.
  -- Optional: a COCO file names its own image, so the annotations can be stored
  -- on their own and a picture attached later.
  image_link    TEXT,
  -- Where that image lives in the bucket, so deleting a row can delete the file
  -- too rather than leaving it orphaned.
  storage_path  TEXT,
  -- The annotations themselves — the file that is uploaded. JSONB, not TEXT, so
  -- the polygons, their categories, and the image size can be queried without
  -- parsing in the client.
  coco_json     JSONB,
  -- Project code as used everywhere else in the portal: MVLC, EBLF, ERHD, GLS, MSCC.
  project       TEXT NOT NULL,
  -- Null for a project whose lots are not grouped (ERHD) or a whole-site map.
  phase         INTEGER,
  -- Section of a split phase map, matching uploads.map_section: A, B, C, or East.
  map_section   TEXT,
  /*
   * Which map tab these annotations belong to, in that tab's own terms:
   * 'whole', 'phase-1', 'phase-2' (a condominium's floors use the same spelling),
   * or 'commercial'. `phase` alone could not tell the whole-site map from the
   * commercial one, since both leave it null.
   */
  slot          TEXT,
  user_id       UUID
);

/*
 * For a database where an earlier version of this file has already been run:
 * CREATE TABLE IF NOT EXISTS skips the table entirely, so columns added since
 * have to be added on their own. Each is a no-op on a table that already has it,
 * which makes the whole file safe to run as many times as you like. This runs
 * before the indexes below, which are defined over these very columns.
 */
ALTER TABLE public.annotated_images ADD COLUMN IF NOT EXISTS storage_path TEXT;
ALTER TABLE public.annotated_images ADD COLUMN IF NOT EXISTS slot TEXT;
ALTER TABLE public.annotated_images ADD COLUMN IF NOT EXISTS coco_json JSONB;
ALTER TABLE public.annotated_images ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();
ALTER TABLE public.annotated_images ADD COLUMN IF NOT EXISTS map_section TEXT;
ALTER TABLE public.annotated_images ALTER COLUMN image_link DROP NOT NULL;

-- Rows written before the slot column existed were keyed by phase alone.
UPDATE public.annotated_images
   SET slot = CASE WHEN phase IS NULL THEN 'whole' ELSE 'phase-' || phase END
 WHERE slot IS NULL;

-- The phase-keyed index cannot hold two slots that both leave phase null.
DROP INDEX IF EXISTS public.annotated_images_project_phase_key;

-- One set of annotations per project map tab; re-uploading replaces it.
CREATE UNIQUE INDEX IF NOT EXISTS annotated_images_project_slot_key
  ON public.annotated_images (project, slot);

ALTER TABLE public.annotated_images ENABLE ROW LEVEL SECURITY;

-- Anyone can view the maps; signed-in portal users can add, change, and remove them.
DROP POLICY IF EXISTS "annotated_images_read" ON public.annotated_images;
CREATE POLICY "annotated_images_read" ON public.annotated_images FOR SELECT USING (true);

DROP POLICY IF EXISTS "annotated_images_insert" ON public.annotated_images;
CREATE POLICY "annotated_images_insert" ON public.annotated_images FOR INSERT TO authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "annotated_images_update" ON public.annotated_images;
CREATE POLICY "annotated_images_update" ON public.annotated_images FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "annotated_images_delete" ON public.annotated_images;
CREATE POLICY "annotated_images_delete" ON public.annotated_images FOR DELETE TO authenticated USING (true);

-- Public bucket, so image_link is a plain public URL like the other galleries.
INSERT INTO storage.buckets (id, name, public)
VALUES ('annotated-images', 'annotated-images', true)
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS "annotated_images_bucket_read" ON storage.objects;
CREATE POLICY "annotated_images_bucket_read" ON storage.objects
  FOR SELECT USING (bucket_id = 'annotated-images');

DROP POLICY IF EXISTS "annotated_images_bucket_insert" ON storage.objects;
CREATE POLICY "annotated_images_bucket_insert" ON storage.objects
  FOR INSERT TO authenticated WITH CHECK (bucket_id = 'annotated-images');

DROP POLICY IF EXISTS "annotated_images_bucket_update" ON storage.objects;
CREATE POLICY "annotated_images_bucket_update" ON storage.objects
  FOR UPDATE TO authenticated USING (bucket_id = 'annotated-images') WITH CHECK (bucket_id = 'annotated-images');

DROP POLICY IF EXISTS "annotated_images_bucket_delete" ON storage.objects;
CREATE POLICY "annotated_images_bucket_delete" ON storage.objects
  FOR DELETE TO authenticated USING (bucket_id = 'annotated-images');

-- Make the new table visible to the API immediately.
NOTIFY pgrst, 'reload schema';
